export const offensiveMagic = Object.freeze([
    { id: 'scorch', name: 'Scorch', power: 1.95, },
    { id: 'scorcher', name: 'Scorcher', power: 2.65, },
    { id: 'giga_blaze', name: 'Giga Blaze', power: 3.7, },
    { id: 'zap', name: 'Zap', power: 2.25, },
    { id: 'zapper', name: 'Zapper', power: 3.15, },
    { id: 'lectro_beam', name: 'Lectro Beam', power: 4.45, },
    { id: 'chill', name: 'Chill', power: 2.1, },
    { id: 'chiller', name: 'Chiller', power: 2.9, },
    { id: 'ice_barrage', name: 'Ice Barrage', power: 4.1, },
    { id: 'gust', name: 'Gust', power: 2.45, },
    { id: 'guster', name: 'Guster', power: 3.2, },
    { id: 'f5_storm', name: 'F5 Storm', power: 4.75, },
    { id: 'mirror_image', name: 'Mirror Image', power: 2.4, },
    { id: 'teleport', name: 'Teleport', power: 3, },
    { id: 'aurora', name: 'Aurora', power: 5, },
    { id: 'curse', name: 'Curse', power: 1.6, },
    { id: 'sleepy', name: 'Sleepy', power: 1.1, },
    { id: 'blind', name: 'Blind', power: 1.4, },
    { id: 'banish', name: 'Banish', power: 2.5, },
    { id: 'drain', name: 'Drain', power: 0, },
    { id: 'swap', name: 'Swap', power: 0, },
    { id: 'pickpocket', name: 'Pickpocket', power: 1.5, },
    { id: 'rust', name: 'Rust', power: 3.6, },
])

export const defensiveMagic = Object.freeze([
    { id: 'm_guard', name: 'M Guard', power: 0.2, },
    { id: 'm_guard_plus', name: 'M Guard+', power: 0.6, },
    { id: 'm_guard_dx', name: 'M Guard DX', power: 0.9, },
    { id: 'refresh', name: 'Refresh', power: 0.2, },
    { id: 'refresh_plus', name: 'Refresh+', power: 0.35, },
    { id: 'refresh_dx', name: 'Refresh DX', power: 0.5, },
    { id: 'super_cure', name: 'Super Cure', power: 0.5, },
    { id: 'seal_magic', name: 'Seal Magic', power: 0.3, },
    { id: 'seal_magic_plus', name: 'Seal Magic+', power: 0.5, },
    { id: 'shock', name: 'Shock', power: 0.6, },
    { id: 'mirror', name: 'Mirror', power: 0.5, },
    { id: 'mg_charge', name: 'MG Charge', power: 0.35, },
    { id: 'at_charge', name: 'AT Charge', power: 0.35, },
    { id: 'df_charge', name: 'DF Charge', power: 0.35, },
    { id: 'sp_charge', name: 'SP Charge', power: 0.35, },
    { id: 'charge_all', name: 'Charge All', power: 0.6, },
    { id: 'charm', name: 'Charm', power: 0.7, },
    { id: 'bounce', name: 'Bounce', power: 0.0, },
    { id: 'super_bounce', name: 'Super Bounce', power: 0.0, },
])
